// =============================================================
// Unit.js — The Object-Oriented Unit Hierarchy
// =============================================================
// This implements the class hierarchy from our design:
//
//        Unit (base class)
//        ├── Ratha (Chariot battalion)
//        ├── Gaja (Elephant battalion)
//        ├── Ashva (Cavalry battalion)
//        ├── Padati (Infantry battalion)
//        └── Maharathi (Named hero — extends Unit directly)
//
// WHY OOP HERE?
// Each unit type shares common behavior (move, take damage, die)
// but has unique rules. OOP lets us define the common stuff ONCE
// in the base class and override only what's different.
//
// IMPORTANT: These are LOGIC classes, not Phaser sprites.
// They hold data and behavior. The TacticalScene renders them
// as colored rectangles for now. Sprite rendering comes later.
// =============================================================

import { UNIT_CLASS_CONFIG } from '../data/UnitClassConfig.js';

// =============================================================
// BASE UNIT CLASS
// =============================================================
// Every unit in the game — from a nameless infantry battalion
// to Arjuna himself — inherits from this class.
//
// This class defines:
//   - Position on the grid (gridX, gridY)
//   - Health (currentHp, maxHp)
//   - Movement (movement points, has-acted flag)
//   - Combat stats (attack, defense, range)
//   - Trait system (array of resolved trait objects)
//   - State tracking (alive, stunned, acted)
// =============================================================

export class Unit {

    constructor(config) {
        // ----------------------------------------------------------
        // IDENTITY
        // ----------------------------------------------------------
        // unitId: Unique identifier for this specific instance.
        //         Generated by UnitManager when spawning.
        //         Example: "pandava_arjuna_001"
        //
        // characterId: Links to characters.json.
        //              null for generic battalions.
        //              "arjuna" for named heroes.
        //
        // unitClass: The Chaturanga type (RATHA, GAJA, etc.)
        //            Determines base stats.
        //
        // faction: "PANDAVA" or "KAURAVA" — which side this unit fights for.
        // ----------------------------------------------------------
        this.unitId = config.unitId || `unit_${Date.now()}_${Math.random().toString(36).substr(2, 5)}`;
        this.characterId = config.characterId || null;
        this.unitClass = config.unitClass || 'PADATI_MELEE';
        this.faction = config.faction || 'PANDAVA';
        this.name = config.name || 'Unknown Unit';

        // ----------------------------------------------------------
        // STATS — Pulled from UnitClassConfig.js
        // ----------------------------------------------------------
        // We look up the base stats for this unit class,
        // then apply any overrides from the config parameter.
        // This allows Role 3 (Level Designer) to create custom
        // units with tweaked stats if needed.
        // ----------------------------------------------------------
        const classStats = UNIT_CLASS_CONFIG[this.unitClass] || UNIT_CLASS_CONFIG['PADATI_MELEE'];

        this.maxHp = config.maxHp || classStats.baseHp;
        this.currentHp = this.maxHp;
        this.movement = config.movement || classStats.baseMovement;
        this.attackRange = config.attackRange || classStats.baseAttackRange;
        this.attackPower = config.attackPower || classStats.baseAttackPower;
        this.defense = config.defense || classStats.baseDefense;
        this.attackType = config.attackType || classStats.attackType;

        // ----------------------------------------------------------
        // POSITION ON THE GRID
        // ----------------------------------------------------------
        // gridX, gridY: The tile coordinates (not pixel coordinates).
        // To convert to pixels: pixelX = gridX * tileSize
        //
        // These are updated by the GridSystem when a unit moves.
        // ----------------------------------------------------------
        this.gridX = config.gridX || 0;
        this.gridY = config.gridY || 0;

        // ----------------------------------------------------------
        // STATE FLAGS
        // ----------------------------------------------------------
        this.isAlive = true;
        this.hasActedThisTurn = false;  // Resets at start of each turn
        this.isStunned = false;         // Set by MaceStunChance trait
        this.morale = 100;              // Affected by aura traits

        // ----------------------------------------------------------
        // TRAIT SYSTEM
        // ----------------------------------------------------------
        // resolvedTraits: An array of FULL trait objects from lore.json.
        // Example for Bhishma:
        //   [
        //     { trait_id: "iccha-mrityu", invulnerable_to_standard_damage: true, ... },
        //     { trait_id: "ganga-putra", ignores_terrain_cost: true, ... }
        //   ]
        //
        // This is populated by UnitManager during spawning.
        // The CombatResolver iterates through these traits
        // during damage calculation.
        // ----------------------------------------------------------
        this.resolvedTraits = config.resolvedTraits || [];

        // ----------------------------------------------------------
        // ASTRA SYSTEM
        // ----------------------------------------------------------
        // resolvedAstras: Array of astra objects this unit can use.
        // consumedAstras: Set of astra IDs that have been used
        //                 (for single-use weapons like Shakti Astra).
        // ----------------------------------------------------------
        this.resolvedAstras = config.resolvedAstras || [];
        this.consumedAstras = new Set();

        // ----------------------------------------------------------
        // VISUAL REFERENCE
        // ----------------------------------------------------------
        // spriteKey: The asset key for rendering.
        // gameObject: Will hold the Phaser sprite/rectangle reference
        //             once TacticalScene creates it.
        // ----------------------------------------------------------
        this.spriteKey = config.spriteKey || null;
        this.gameObject = null;
    }

    // =============================================================
    // TRAIT QUERIES
    // =============================================================
    // These helper methods let other systems ask questions about
    // this unit's traits without knowing the trait data structure.
    // =============================================================

    /**
     * Check if this unit has a specific trait by ID.
     * Example: unit.hasTrait('iccha-mrityu') → true for Bhishma
     */
    hasTrait(traitId) {
        return this.resolvedTraits.some(t => t.trait_id === traitId);
    }

    /**
     * Check if this unit is invulnerable to standard damage.
     * Returns true if ANY of its traits grant invulnerability.
     */
    isInvulnerable() {
        return this.resolvedTraits.some(t => t.invulnerable_to_standard_damage === true);
    }

    /**
     * Check if this unit ignores terrain movement costs.
     * Returns true if ANY trait grants terrain immunity.
     * Example: Ghatotkacha (rakshasa-prince) flies over everything.
     */
    ignoresTerrainCost() {
        return this.resolvedTraits.some(t => t.ignores_terrain_cost === true);
    }

    /**
     * Get all handler strings for this unit's traits.
     * Returns: ["CheckShikhandiPresence()", "IgnoreRiverTerrain()"]
     * Used by TraitHandlers.js to know which functions to run.
     */
    getTraitHandlers() {
        return this.resolvedTraits.map(t => t.custom_script_handler);
    }

    // =============================================================
    // COMBAT METHODS
    // =============================================================

    /**
     * Apply damage to this unit.
     * Returns the actual damage dealt (after defense).
     * Does NOT handle invulnerability — that's CombatResolver's job.
     */
    takeDamage(amount) {
        const actualDamage = Math.max(0, amount);
        this.currentHp -= actualDamage;

        if (this.currentHp <= 0) {
            this.currentHp = 0;
            this.isAlive = false;
        }

        return actualDamage;
    }

    /**
     * Heal this unit.
     * Cannot exceed maxHp.
     */
    heal(amount) {
        if (!this.isAlive) return 0;
        const before = this.currentHp;
        this.currentHp = Math.min(this.maxHp, this.currentHp + amount);
        return this.currentHp - before;
    }

    /**
     * Get HP as a percentage (0 to 1).
     * Used by trigger conditions: "UNIT_HP_BELOW_PERCENT"
     */
    getHpPercent() {
        return this.currentHp / this.maxHp;
    }

    // =============================================================
    // TURN MANAGEMENT
    // =============================================================

    /**
     * Called at the start of each turn for this unit.
     * Resets the action flag and processes per-turn effects.
     */
    startTurn() {
        this.hasActedThisTurn = false;

        // Process stun: if stunned, skip this turn
        if (this.isStunned) {
            this.isStunned = false;     // Stun wears off
            this.hasActedThisTurn = true; // But can't act THIS turn
        }
    }

    /**
     * Mark this unit as having completed its action for this turn.
     */
    endAction() {
        this.hasActedThisTurn = true;
    }

    /**
     * Can this unit still act this turn?
     */
    canAct() {
        return this.isAlive && !this.hasActedThisTurn;
    }
}


// =============================================================
// MAHARATHI CLASS — Named Hero Extension
// =============================================================
// Maharathis are the legendary warriors: Arjuna, Karna, Bhishma.
// They use MAHARATHI base stats (much higher than regular units)
// and have access to astras and complex trait interactions.
//
// This class extends Unit and adds:
//   - Astra usage logic
//   - Multi-trait interaction handling
//   - Canonical name and portrait for VN integration
// =============================================================

export class Maharathi extends Unit {

    constructor(config) {
        // Call the parent constructor with MAHARATHI stats
        super({
            ...config,
            unitClass: 'MAHARATHI'
        });

        // ----------------------------------------------------------
        // HERO-SPECIFIC PROPERTIES
        // ----------------------------------------------------------
        this.canonicalName = config.canonicalName || 'Unknown Warrior';
        this.portraitKey = config.portraitKey || null;

        // ----------------------------------------------------------
        // WEAPON TYPE
        // ----------------------------------------------------------
        // Derived from the sprite key.
        // 'ranged' for chariot warriors (bow)
        // 'melee' for mace/sword warriors
        // 'none' for non-combatants like Krishna
        // ----------------------------------------------------------
        this.weaponType = config.weaponType || 'ranged';

        // Override attackType based on weapon
        if (this.weaponType === 'melee') {
            this.attackType = 'melee';
            this.attackRange = 1;
        }
        if (this.weaponType === 'none') {
            this.attackType = 'none';
            this.attackRange = 0;
            this.attackPower = 0;
        }
                // ----------------------------------------------------------
        // CHARIOT CREW (warrior + optional charioteer = ONE grid unit)
        // ----------------------------------------------------------
        // charioteerTier:
        //   'NONE'     — no driver / not a chariot pair
        //   'ORDINARY' — unnamed sūta — no trait buffs
        //   'HERO'     — Krishna, Shalya, etc. — support traits at SARATHI_BUFF_SCALE
        // ----------------------------------------------------------
        this.crew = {
            warriorId: config.crew?.warriorId || config.characterId || null,
            charioteerId: config.crew?.charioteerId || null,
            charioteerTier: config.crew?.charioteerTier || 'NONE',
            charioteerName: config.crew?.charioteerName || null,
            charioteerTraits: config.crew?.charioteerTraits || []
        };

        // Hero-sarathi support effectiveness (movement, auras, morale buffs)
        this.sarathiBuffScale = config.sarathiBuffScale ?? 0.7; // 70%
        
    }

    // =============================================================
    // ASTRA METHODS
    // =============================================================

    /**
     * Check if this Maharathi can use a specific astra.
     * Returns { allowed: boolean, reason: string }
     */
    canUseAstra(astraId, currentDharma) {
        // Check 1: Does this hero have access to this astra?
        const astra = this.resolvedAstras.find(a => a.astra_id === astraId);
        if (!astra) {
            return {
                allowed: false,
                reason: `${this.canonicalName} does not know the ${astraId}.`
            };
        }

        // Check 2: Has this single-use astra already been consumed?
        if (this.consumedAstras.has(astraId)) {
            return {
                allowed: false,
                reason: `The ${astra.name} has already been expended.`
            };
        }

        // Check 3: Enough dharma?
        if (currentDharma < astra.dharma_cost) {
            return {
                allowed: false,
                reason: `Insufficient Dharma to invoke the ${astra.name}. Required: ${astra.dharma_cost}, Current: ${currentDharma}.`
            };
        }

        // Check 4: Krishna's weapons restriction
        if (this.weaponType === 'none') {
            return {
                allowed: false,
                reason: `${this.canonicalName} has vowed not to wield weapons in this war.`
            };
        }

        return { allowed: true, reason: '' };
    }

    /**
     * Use an astra against a target.
     * Returns the damage multiplier and marks single-use astras as consumed.
     */
    useAstra(astraId) {
        const astra = this.resolvedAstras.find(a => a.astra_id === astraId);
        if (!astra) return { multiplier: 1.0, dharmaCost: 0 };

        // Mark single-use astras as consumed
        const singleUseAstras = ['shakti-astra', 'narayanastra'];
        if (singleUseAstras.includes(astraId)) {
            this.consumedAstras.add(astraId);
        }

        return {
            multiplier: astra.damage_multiplier,
            dharmaCost: astra.dharma_cost,
            name: astra.name,
            restrictions: astra.restrictions
        };
    }
        /**
     * All traits that affect this token: warrior at 100%, hero-sarathi support at scale.
     * Ordinary driver contributes nothing.
     */
    getEffectiveTraitEntries() {
        const entries = this.resolvedTraits.map(t => ({
            trait: t,
            source: 'warrior',
            scale: 1.0
        }));

        if (this.crew.charioteerTier === 'HERO' && this.crew.charioteerTraits?.length) {
            const scale = this.sarathiBuffScale;
            this.crew.charioteerTraits.forEach(t => {
                entries.push({
                    trait: t,
                    source: 'charioteer',
                    scale
                });
            });
        }
        // ORDINARY / NONE → no charioteer traits

        return entries;
    }

    /** Override: true if warrior OR (hero charioteer) has the trait id */
    hasTrait(traitId) {
        if (super.hasTrait(traitId)) return true;
        if (this.crew.charioteerTier !== 'HERO') return false;
        return (this.crew.charioteerTraits || []).some(t => t.trait_id === traitId);
    }

    getTraitHandlers() {
        return this.getEffectiveTraitEntries().map(e => e.trait.custom_script_handler);
    }

    /**
     * Movement bonus from hero sarathi only (e.g. BoostChariotMovement), scaled.
     * Ordinary driver: 0.
     */
    getSarathiMovementBonus() {
        if (this.crew.charioteerTier !== 'HERO') return 0;

        let bonus = 0;
        for (const t of this.crew.charioteerTraits || []) {
            const h = t.custom_script_handler || '';
            if (h.startsWith('BoostChariotMovement')) {
                const m = h.match(/\(([\d.]+)\)/);
                const raw = m ? Number(m[1]) : 2;
                bonus += raw * this.sarathiBuffScale;
            }
        }
        return Math.floor(bonus); // e.g. 2 * 0.7 → 1 extra tile
    }

    /** Display name: "Arjuna (Krishna)" vs "Arjuna" */
    getDisplayName() {
        if (this.crew.charioteerTier === 'HERO' && this.crew.charioteerName) {
            return `${this.name} (${this.crew.charioteerName.split(' ')[0]})`;
        }
        if (this.crew.charioteerTier === 'ORDINARY') {
            return `${this.name} [ratha]`;
        }
        return this.name;
    }
}