class BootScene extends Phaser.Scene {
  constructor() {
    super('BootScene');
  }

  preload() {
    // 1. Data Layer: The single source of truth for Role 4
    // We are loading the vertical slice (Bhishma Parva)
    this.load.json('timeline', 'data/parvas/bhishma-parva/timeline.json');
    this.load.json('directives', 'data/parvas/bhishma-parva/directives.json');

    // Global Lore & Unit Archetypes
    this.load.json('lore', 'data/global/lore.json');
    this.load.json('characters', 'data/global/characters.json');
    this.load.json('unit_classes', 'data/global/unit_classes.json');

    // 2. Map JSON Data (Generated by Role 3)
    this.load.json('map_kurukshetra_center', 'data/maps/map_kurukshetra_center.json');

    // 3. Asset Loading (Visuals/Audio)
    // NOTE: In production, we iterate through timeline.json to batch-load what we need.
    // We will place placeholders for the vertical slice here.

    // Tileset UI
    // this.load.image('tileset_kurukshetra', 'assets/tilesets/tileset_kurukshetra.png');
    // Unit Sprites (e.g. from characters.json base_sprite_key)
    // this.load.image('spr_bhishma_chariot', 'assets/sprites/bhishma.png');
    // this.load.image('spr_arjuna_chariot', 'assets/sprites/arjuna.png');
  }

  create() {
    console.log('[BootScene] All JSON constraints loaded.');

    // Fetch the global GameManager from the registry
    const gm = this.game.registry.get('gameManager');

    // Hydrate the GameManager with the core JSON data
    gm.directivesData = this.cache.json.get('directives');

    // We'd typically inject the lore and unit_classes into Role 3's DataStore here
    // gm.dataStore.loadLore(this.cache.json.get('lore'));
    // gm.dataStore.loadUnits(this.cache.json.get('unit_classes'));

    console.log('[BootScene] GameManager hydrated with Bhishma Parva Directives.');

    // Transition to the Main Game logic
    this.scene.start('MainScene');
  }
}

export default BootScene;